
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS stud_categ;
CREATE TABLE students (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
name VARCHAR (32),
surname VARCHAR (32)
);

CREATE TABLE categories (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
name VARCHAR (32));

CREATE TABLE courses (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
name VARCHAR (32),
category_id INTEGER
);

CREATE TABLE student_2_course (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
student_id INTEGER,
course_id INTEGER
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;